# Конфигурационный файл плагина BoatSpeed

# Интервал ускорения лодок в секундах
intervalSeconds: 10

# Множитель скорости ускорения лодок
speedMultiplier: 1.5

# Начальная скорость лодок
initialSpeed: 0.4

# Показывать ли ActionBar с таймером ускорения
showActionBar: true
